version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/revista-back
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - postgres
  postgres:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=revista
    ports:
      - 5439:5432

volumes:
  postgres_data:
