# Generated by Django 5.0.1 on 2024-01-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_organization_and_customer_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='tg_id',
            field=models.BigIntegerField(blank=True, db_comment='Telegram ID', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tg_nickname',
            field=models.TextField(blank=True, db_comment='Telegram nickname', null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='tg_api_hash',
            field=models.TextField(blank=True, db_comment='Telegram API hash аккаунта для рассылки', null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='tg_api_id',
            field=models.BigIntegerField(blank=True, db_comment='Telegram API ID аккаунта для рассылки', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tg_id',
            field=models.BigIntegerField(blank=True, db_comment='Telegram ID', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tg_nickname',
            field=models.TextField(blank=True, db_comment='Telegram nickname', null=True, unique=True),
        ),
    ]
