# Generated by Django 5.0.1 on 2024-01-22 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_user_organization_alter_organization_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='sender_user_id',
            new_name='sender_user',
        ),
        migrations.AddField(
            model_name='customer',
            name='organizations',
            field=models.ManyToManyField(through='database.CustomerOrganization', to='database.organization'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='tg_api_id',
            field=models.BigIntegerField(blank=True, db_comment='Telegram API ID аккаунта для рассылки', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, db_comment='[FK]', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database.organization'),
        ),
    ]
