# Generated by Django 5.0.1 on 2024-02-07 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_alter_messages_message_alter_messages_sender_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(db_comment='[PK]', primary_key=True, serialize=False)),
                ('name', models.CharField(db_comment='Агенты организации', max_length=50)),
                ('conversation_goal', models.TextField()),
                ('business_company', models.TextField()),
                ('prompt', models.TextField()),
                ('dialogue_analysis', models.TextField()),
                ('tg_api_id', models.BigIntegerField(blank=True, db_comment='Telegram API ID агента', null=True)),
                ('tg_api_hash', models.TextField(blank=True, db_comment='Telegram API hash агента', null=True)),
            ],
            options={
                'db_table': 'agents',
            },
        ),
        migrations.CreateModel(
            name='OrganizationAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(auto_now_add=True, db_comment='Дата и время создания записи')),
                ('agent', models.ForeignKey(db_comment='[FK]', on_delete=django.db.models.deletion.DO_NOTHING, to='database.agent')),
                ('organization', models.ForeignKey(db_comment='[FK]', on_delete=django.db.models.deletion.DO_NOTHING, to='database.organization')),
            ],
            options={
                'db_table': 'organization_agent',
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='organizations',
            field=models.ManyToManyField(through='database.OrganizationAgent', to='database.organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='agents',
            field=models.ManyToManyField(through='database.OrganizationAgent', to='database.agent'),
        ),
    ]
