# Generated by Django 5.0.1 on 2024-02-13 18:39

from database.validators import validate_tg_nickname
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_agent_organizationagent_agent_organizations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='tg_nickname',
            field=models.TextField(blank=True, db_comment='Telegram nickname', null=True, validators=[validate_tg_nickname]),
        ),
    ]
