# Generated by Django 5.0.1 on 2024-02-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_alter_customer_tg_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='tg_api_hash',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='tg_api_id',
        ),
        migrations.AddField(
            model_name='organization',
            name='tin',
            field=models.CharField(db_comment='ИНН', default='', max_length=12, unique=True),
        ),
    ]
