# Generated by Django 5.0.1 on 2024-02-14 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_remove_organization_tg_api_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(db_comment='[PK]', primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_comment='Имя', max_length=50)),
                ('last_name', models.CharField(db_comment='Фамилия', max_length=50)),
                ('tg_nickname', models.TextField(blank=True, db_comment='Telegram nickname', null=True)),
                ('ctime', models.DateTimeField(auto_now_add=True, db_comment='Дата и время создания записи')),
            ],
            options={
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='OrganizationContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(auto_now_add=True, db_comment='Дата и время создания записи')),
                ('contact', models.ForeignKey(db_comment='[FK]', on_delete=django.db.models.deletion.DO_NOTHING, to='database.contact')),
                ('organization', models.ForeignKey(db_comment='[FK]', on_delete=django.db.models.deletion.DO_NOTHING, to='database.organization')),
            ],
            options={
                'db_table': 'organization__contact',
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='organization',
            field=models.ManyToManyField(related_name='Org_contacts', through='database.OrganizationContact', to='database.organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='contacts',
            field=models.ManyToManyField(related_name='organizations_contacts', through='database.OrganizationContact', to='database.contact'),
        ),
    ]
